export enum EnumUserAction {
  UPDATE_PROFILE_CART_START = 'UPDATE_PROFILE_CART_START',
  UPDATE_PROFILE_CART_SUCCESS = 'UPDATE_PROFILE_CART_SUCCESS',
  UPDATE_PROFILE_CART_FILL = 'UPDATE_PROFILE_CART_FILL',

  DELETE_PROFILE_CART_START = 'DELETE_PROFILE_CART_START',
  DELETE_PROFILE_CART_SUCCESS = 'DELETE_PROFILE_CART_SUCCESS',
  DELETE_PROFILE_CART_FILL = 'DELETE_PROFILE_CART_FILL',
}
