export enum EnumCartAction {
  UPDATE_ITEM_START = 'UPDATE_ITEM_START',
  UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_FILL = 'UPDATE_ITEM_FILL',

  DELETE_ITEM_START = 'DELETE_ITEM_START',
  DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCES',
  DELETE_ITEM_FILL = 'DELETE_ITEM_FILL',
}
